#!/bin/sh

# Quick and shitty make/rake/whatever dropin for my common tasks

BEGIN() {
    set -x
}

FINISH() {
    set +x
}

appcfg() {
    BEGIN
    appcfg.py --oauth2 "$@"
    FINISH
}

case $1 in
    deploy)
        appcfg update .
        ;;
    rollback)
        appcfg rollback .
        ;;
    debug_logs)
        appcfg --severity 0 request_logs . logs.txt
        ;;
    logs)
        appcfg request_logs . logs.txt
        ;;

    *)
        echo "Unknown command '$1'"
        ;;
esac

